/**
 * One-time migration: convert NanoClaw's existing wiki layout to OpenClaw-
 * compatible vault structure.
 *
 * Run with --dry-run first to see what will change. Run without --dry-run to
 * apply.
 *
 * What it does:
 *   1. Walks the existing wiki/ tree (NanoClaw layout: businesses/, people/,
 *      personal/, systems/, concepts/, arc/, top-level pages)
 *   2. Maps each page to its OpenClaw destination (entities/, concepts/,
 *      syntheses/) based on category frontmatter
 *   3. Adds OpenClaw-required frontmatter: id, pageType, sourceIds, claims,
 *      contradictions, questions, confidence, status, updatedAt
 *   4. Preserves NanoClaw-specific extras (tags, created, original category)
 *      so we don't lose information
 *   5. Moves files to new locations (wikilinks resolve by basename so
 *      [[wiki-link]] references keep working)
 *   6. Creates .openclaw-wiki/ state directory with config.json
 *   7. Backfills wiki/log.md → .openclaw-wiki/log.jsonl
 *   8. Creates seed files (AGENTS.md, WIKI.md, inbox.md) if missing
 *
 * NOT TOUCHED:
 *   - sources/ directory (308 raw files stay as-is — bridge will manage them)
 *   - The Obsidian .obsidian/ config dir
 *   - wiki/index.md (will be regenerated by compile, but kept as-is for now)
 *   - The _ingest-plan.md file (one-time setup artifact, leave alone)
 */

import fs from 'fs';
import path from 'path';

import {
  parseWikiPage,
  readWikiPage,
  serializeWikiPage,
  WikiPageFrontmatter,
  WikiPageKind,
} from './markdown.js';

const VAULT_ROOT = path.resolve('groups/telegram_wiki-inbox/wiki');
const STATE_DIR = path.join(VAULT_ROOT, '.openclaw-wiki');
const TIMESTAMP = new Date().toISOString();

interface MigrationStep {
  fromPath: string;
  toPath: string;
  oldKind: string;
  newKind: WikiPageKind;
  newFrontmatter: WikiPageFrontmatter;
  bodyLength: number;
}

interface MigrationPlan {
  pages: MigrationStep[];
  newDirs: string[];
  newSeedFiles: { path: string; content: string }[];
  logBackfill: { sourcePath: string; targetPath: string; eventCount: number };
  warnings: string[];
}

// =============================================================================
// Category → kind + directory mapping
// =============================================================================

function categoryToKind(category: string | undefined): WikiPageKind {
  switch ((category || '').toLowerCase()) {
    case 'businesses':
    case 'people':
    case 'personal':
    case 'systems':
      return 'entity';
    case 'concepts':
      return 'concept';
    case 'arc':
      return 'synthesis';
    default:
      // Unknown category — best-effort default
      return 'entity';
  }
}

function kindToDir(kind: WikiPageKind): string {
  // Legacy 5-kind map — this migration script only produces these
  // kinds. Phase 3 MECE kinds (person, company, etc.) are handled by
  // migrate-vault.ts which takes over after this script runs.
  switch (kind) {
    case 'entity':
      return 'entities';
    case 'concept':
      return 'concepts';
    case 'source':
      return 'sources';
    case 'synthesis':
      return 'syntheses';
    case 'report':
      return 'reports';
    default:
      return 'entities';
  }
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildPageId(kind: WikiPageKind, slug: string): string {
  return `${kind}.${slug}`;
}

// =============================================================================
// Frontmatter transformation
// =============================================================================

function transformFrontmatter(
  oldFm: WikiPageFrontmatter & {
    category?: string;
    tags?: string[];
    created?: string;
    sources?: string[];
    related?: string[];
  },
  filename: string,
  kind: WikiPageKind,
): WikiPageFrontmatter {
  const slug = path.basename(filename, '.md');
  const id = buildPageId(kind, slug);

  // Carry over existing fields, then enforce OpenClaw schema.
  const next: WikiPageFrontmatter & Record<string, unknown> = {
    // OpenClaw required fields first (controls field order in output)
    id,
    pageType: kind,
    title: oldFm.title || slug,
    sourceIds: Array.isArray(oldFm.sources) ? oldFm.sources : [],
    claims: [],
    contradictions: [],
    questions: [],
    confidence: 0.7, // sensible middling default; lint will flag <0.5
    status: 'active',
    updatedAt: oldFm.updatedAt || oldFm.created || TIMESTAMP,
    // NanoClaw extras preserved (lint ignores unknown fields)
    tags: oldFm.tags || [],
    originalCategory: oldFm.category,
    createdAt: oldFm.created,
  };

  // Drop the old `related` field — relations are computed at compile time
  // from sourceIds + extracted wikilinks. The inline [[wiki-links]] in the
  // body remain and are the source of truth for cross-references.

  // Strip undefined fields for clean output
  for (const key of Object.keys(next)) {
    if (next[key] === undefined) delete next[key];
  }

  return next;
}

// =============================================================================
// Plan builder — pure, no I/O writes
// =============================================================================

function findExistingPages(): string[] {
  const pages: string[] = [];
  // Skip raw/state/Obsidian dirs. Note: target dirs (entities/, concepts/,
  // syntheses/, reports/) are NOT skipped because:
  //   - concepts/ already contains source content in the current layout
  //   - re-running migration on already-migrated files is idempotent
  //     (transform produces the same output for OpenClaw-shaped frontmatter)
  const skipDirs = new Set([
    'sources',
    'logs',
    '.obsidian',
    '.openclaw-wiki',
    '_attachments',
    '_views',
  ]);
  const skipFiles = new Set(['_ingest-plan.md', 'log.md', 'index.md']);

  const walk = (dir: string) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (skipDirs.has(entry.name)) continue;
        walk(full);
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        if (skipFiles.has(entry.name)) continue;
        pages.push(full);
      }
    }
  };
  walk(VAULT_ROOT);

  // Top-level pages that are NOT index.md / log.md / _ingest-plan.md
  const topLevel = fs
    .readdirSync(VAULT_ROOT, { withFileTypes: true })
    .filter(
      (e) => e.isFile() && e.name.endsWith('.md') && !skipFiles.has(e.name),
    )
    .map((e) => path.join(VAULT_ROOT, e.name));
  for (const f of topLevel) {
    if (!pages.includes(f)) pages.push(f);
  }

  return pages.sort();
}

function buildPlan(): MigrationPlan {
  const plan: MigrationPlan = {
    pages: [],
    newDirs: ['entities', 'concepts', 'syntheses', 'sources', 'reports'].map(
      (d) => path.join(VAULT_ROOT, d),
    ),
    newSeedFiles: [],
    logBackfill: {
      sourcePath: path.join(VAULT_ROOT, 'log.md'),
      targetPath: path.join(STATE_DIR, 'log.jsonl'),
      eventCount: 0,
    },
    warnings: [],
  };

  // Pages
  for (const filePath of findExistingPages()) {
    let parsed;
    try {
      parsed = readWikiPage(filePath);
    } catch (err) {
      plan.warnings.push(
        `Could not parse ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
      );
      continue;
    }
    const oldFm = parsed.frontmatter as WikiPageFrontmatter & {
      category?: string;
      tags?: string[];
      created?: string;
      sources?: string[];
    };
    const filename = path.basename(filePath);
    const kind = categoryToKind(oldFm.category);
    const newDir = path.join(VAULT_ROOT, kindToDir(kind));
    const toPath = path.join(newDir, filename);
    const newFm = transformFrontmatter(oldFm, filename, kind);

    plan.pages.push({
      fromPath: filePath,
      toPath,
      oldKind: oldFm.category || '(none)',
      newKind: kind,
      newFrontmatter: newFm,
      bodyLength: parsed.body.length,
    });

    // Note: when filePath === toPath, the file stays put — only frontmatter
    // is rewritten. That's normal for `concepts/` (already in the right dir).
    // No warning needed.
  }

  // Detect basename collisions
  const seen = new Map<string, string>();
  for (const step of plan.pages) {
    const basename = path.basename(step.toPath);
    if (seen.has(basename)) {
      plan.warnings.push(
        `BASENAME COLLISION: ${basename} appears in both ${seen.get(basename)} and ${step.fromPath}. Wikilinks may resolve ambiguously.`,
      );
    }
    seen.set(basename, step.fromPath);
  }

  // Seed files (only if missing)
  const seedDefinitions: { name: string; content: string }[] = [
    {
      name: 'AGENTS.md',
      content: `# Agents Guide

This vault is OpenClaw-compatible. Agents working with it should follow these rules:

1. **Page kinds** are tracked via the \`pageType\` frontmatter field. Valid values: \`entity\`, \`concept\`, \`source\`, \`synthesis\`, \`report\`. The directory must match (entities/ for entity, concepts/ for concept, etc).
2. **Cross-references** use \`[[wiki-link]]\` syntax. Resolved by basename across the vault.
3. **The \`## Related\` block** on each page is auto-generated by \`npm run wiki:compile\` from \`sourceIds\` + extracted wikilinks. Do not edit it manually — it lives between \`<!-- openclaw:wiki:related:start --> ... <!-- openclaw:wiki:related:end -->\` markers and gets overwritten.
4. **Generated content blocks** (\`<!-- openclaw:wiki:generated:* -->\`) are owned by automation. Human edits go inside \`<!-- openclaw:human:* -->\` blocks where present, or in regular sections outside the managed markers.
5. **Source pages** (\`sources/bridge-*.md\`) are fully regenerated by the bridge sync. Do not edit them — write notes in a separate synthesis or entity page that links to the bridged source.
6. **MEMORY.md** at the workspace level is cron-managed (rewritten daily at 23:00 CET). Never write to it directly.
7. **The \`pending-ingest.json\`** file in \`.openclaw-wiki/\` is the bridge sync's "new sources to process" marker. Read it on every wake-up and ingest the listed sources before doing other work.
`,
    },
    {
      name: 'WIKI.md',
      content: `# Wiki

A persistent, structured, interlinked markdown wiki maintained by Janus Nano for Maurizio. Domain: comprehensive — personal life, businesses, things tried, things to try, frameworks, decisions, people, tools.

**Vault mode**: bridge (auto-pulls memory files into \`sources/\` from configured paths)
**Render mode**: obsidian (\`[[wiki-links]]\`)
**OpenClaw compatible**: yes — vault structure matches \`openclaw/openclaw extensions/memory-wiki\`

## Layout

- \`entities/\` — people, businesses, products, tools, named things
- \`concepts/\` — frameworks, methodologies, mental models
- \`syntheses/\` — narrative arcs, time-bounded reflections, executive summaries
- \`sources/\` — raw immutable source pages (bridge-imported memory + manual drops)
- \`reports/\` — auto-generated dashboards (lint, contradictions, stale pages, etc)
- \`.openclaw-wiki/\` — state directory: source-sync.json, agent-digest.json, claims.jsonl, log.jsonl, config.json
- \`_attachments/\`, \`_views/\` — Obsidian conventions (currently unused)

## Three operations

| Op | When | What |
|---|---|---|
| **Bridge** | Daily at 23:30 CET, or before any wiki-inbox container spawn | Pull new memory files into \`sources/\`, drop \`pending-ingest.json\` |
| **Ingest** | Janus, on every wake-up if pending-ingest.json exists | Read new sources, update entity/concept/synthesis pages |
| **Compile** | After every bridge sync (auto), or manually via \`npm run wiki:compile\` | Refresh \`## Related\` blocks, regenerate indexes, rewrite \`agent-digest.json\` + \`claims.jsonl\` |
| **Lint** | Weekly Sunday 10:00 CET, or manually via \`npm run wiki:lint\` | Check contradictions, stale pages, missing evidence, broken links |

## CLI

\`\`\`bash
npm run wiki:bridge   # Manual bridge sync
npm run wiki:compile  # Recompute related blocks + caches
npm run wiki:lint     # Run health checks, write to reports/lint.md
\`\`\`
`,
    },
    {
      name: 'inbox.md',
      content: `# Inbox

Drop unstructured notes here. Process into entity/concept/synthesis pages later (or have Janus do it).

---
`,
    },
  ];
  for (const seed of seedDefinitions) {
    const fullPath = path.join(VAULT_ROOT, seed.name);
    if (!fs.existsSync(fullPath)) {
      plan.newSeedFiles.push({ path: fullPath, content: seed.content });
    }
  }

  // Log backfill — count current entries in log.md
  if (fs.existsSync(plan.logBackfill.sourcePath)) {
    const md = fs.readFileSync(plan.logBackfill.sourcePath, 'utf-8');
    plan.logBackfill.eventCount = (md.match(/^## \[/gm) || []).length;
  }

  return plan;
}

// =============================================================================
// Apply
// =============================================================================

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function backfillLogJsonl(plan: MigrationPlan): void {
  const { sourcePath, targetPath } = plan.logBackfill;
  if (!fs.existsSync(sourcePath)) return;
  const md = fs.readFileSync(sourcePath, 'utf-8');
  // Parse `## [YYYY-MM-DD] action | description` blocks into events
  const blockRe =
    /^## \[(\d{4}-\d{2}-\d{2})\]\s+(\w+)\s*\|\s*(.+?)\n([\s\S]*?)(?=\n## \[|\n*$)/gm;
  const events: Array<{ ts: string; type: string; data: unknown }> = [];
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(md)) !== null) {
    const [, date, action, title, body] = m;
    events.push({
      ts: `${date}T00:00:00.000Z`,
      type: action,
      data: { title: title.trim(), body: body.trim() },
    });
  }
  // Add a single migration event at the end
  events.push({
    ts: TIMESTAMP,
    type: 'init',
    data: {
      action: 'migrate-to-openclaw-vault-layout',
      backfilledFromLogMd: events.length,
      pageCount: plan.pages.length,
    },
  });
  ensureDir(path.dirname(targetPath));
  const jsonl = events.map((e) => JSON.stringify(e)).join('\n') + '\n';
  fs.writeFileSync(targetPath, jsonl);
}

function applyPlan(plan: MigrationPlan): void {
  // 1. Create new dirs
  for (const dir of plan.newDirs) {
    ensureDir(dir);
  }
  ensureDir(STATE_DIR);
  ensureDir(path.join(STATE_DIR, 'cache'));

  // 2. Move pages with transformed frontmatter
  for (const step of plan.pages) {
    const parsed = readWikiPage(step.fromPath);
    const newContent = serializeWikiPage(step.newFrontmatter, parsed.body);
    ensureDir(path.dirname(step.toPath));
    fs.writeFileSync(step.toPath, newContent);
    if (step.fromPath !== step.toPath) {
      fs.unlinkSync(step.fromPath);
    }
  }

  // 3. Clean up empty old dirs
  const oldDirs = ['businesses', 'people', 'personal', 'systems', 'arc'];
  for (const old of oldDirs) {
    const dir = path.join(VAULT_ROOT, old);
    if (fs.existsSync(dir)) {
      const remaining = fs.readdirSync(dir);
      if (remaining.length === 0) {
        fs.rmdirSync(dir);
      }
    }
  }

  // 4. Write seed files (only if missing)
  for (const seed of plan.newSeedFiles) {
    fs.writeFileSync(seed.path, seed.content);
  }

  // 5. Write .openclaw-wiki/config.json
  const config = {
    version: 1,
    vaultMode: 'bridge',
    renderMode: 'obsidian',
    createdAt: TIMESTAMP,
    migration: {
      from: 'nanoclaw-pre-openclaw-layout',
      at: TIMESTAMP,
      pageCount: plan.pages.length,
    },
  };
  fs.writeFileSync(
    path.join(STATE_DIR, 'config.json'),
    JSON.stringify(config, null, 2) + '\n',
  );

  // 6. Backfill log.md → log.jsonl
  backfillLogJsonl(plan);
}

// =============================================================================
// Reporting
// =============================================================================

function printPlan(plan: MigrationPlan): void {
  console.log('Wiki migration plan');
  console.log('===================');
  console.log();
  console.log(`Vault: ${VAULT_ROOT}`);
  console.log(`Pages to migrate: ${plan.pages.length}`);
  console.log(`New seed files: ${plan.newSeedFiles.length}`);
  console.log(`Log entries to backfill: ${plan.logBackfill.eventCount}`);
  console.log();

  // Group by destination kind
  const byKind = new Map<string, MigrationStep[]>();
  for (const step of plan.pages) {
    const arr = byKind.get(step.newKind) || [];
    arr.push(step);
    byKind.set(step.newKind, arr);
  }

  for (const [kind, steps] of byKind) {
    console.log(`\n${kind.toUpperCase()} (${steps.length}):`);
    for (const step of steps) {
      const from = path.relative(VAULT_ROOT, step.fromPath);
      const to = path.relative(VAULT_ROOT, step.toPath);
      const arrow = from === to ? '   (in place)   ' : ' → ';
      console.log(
        `  ${from.padEnd(45)}${arrow}${from === to ? '' : to.padEnd(40)}  [${step.oldKind} → ${step.newKind}]`,
      );
    }
  }

  if (plan.warnings.length > 0) {
    console.log('\nWARNINGS:');
    for (const w of plan.warnings) {
      console.log(`  ! ${w}`);
    }
  }

  console.log('\nNew directories:');
  for (const d of plan.newDirs) {
    console.log(`  + ${path.relative(VAULT_ROOT, d)}/`);
  }

  console.log('\nState dir:');
  console.log(`  + ${path.relative(VAULT_ROOT, STATE_DIR)}/`);
  console.log(`  + ${path.relative(VAULT_ROOT, STATE_DIR)}/config.json`);
  console.log(`  + ${path.relative(VAULT_ROOT, STATE_DIR)}/log.jsonl`);
  console.log(`  + ${path.relative(VAULT_ROOT, STATE_DIR)}/cache/`);

  console.log('\nSeed files:');
  for (const s of plan.newSeedFiles) {
    console.log(`  + ${path.relative(VAULT_ROOT, s.path)}`);
  }

  console.log('\nFiles preserved (not touched):');
  console.log(`  - sources/ (308 raw bridge sources)`);
  console.log(`  - .obsidian/`);
  console.log(
    `  - log.md (kept as-is for human reference; jsonl is the new source of truth)`,
  );
  console.log(`  - _ingest-plan.md`);
  console.log(`  - index.md (will be regenerated by compile)`);
}

// =============================================================================
// Entry point
// =============================================================================

function main(): void {
  const args = process.argv.slice(2);
  const dryRun = !args.includes('--apply');

  const plan = buildPlan();
  printPlan(plan);

  if (dryRun) {
    console.log('\n[DRY RUN] No files have been modified.');
    console.log('To apply: npx tsx src/wiki/migrate-from-nanoclaw.ts --apply');
    return;
  }

  console.log('\n[APPLY] Migrating now...');
  applyPlan(plan);
  console.log('\nMigration complete.');
  console.log(`\nNext: verify the result with`);
  console.log(
    `  find ${path.relative(process.cwd(), VAULT_ROOT)} -maxdepth 2 -type f -name '*.md' | sort`,
  );
}

main();
